Hindi translation added for CSR/SSR question
h5bp/Front-end-Developer-Interview-Questions pull request #876
Opened 2024-02-07 19:59 UTC by arp55

## Type of change

- [ ] Other (please elaborate)  - Hindi translation added for a question

# Checklist:

- [ ] My content follows the style guidelines of this project
- [ ] I have performed a self-review of my own content

2024-03-04 18:42 UTC, roblarsen requested changes

2024-03-04 18:42 UTC, roblarsen commented on src/questions/javascript-questions.md
> +* What are the differences between variables created using `let`, `var` or `const`? What is temporal dead zone?
Please remove the new question

2024-03-05 08:50 UTC, arp55 commented on src/questions/javascript-questions.md
> +* What are the differences between variables created using `let`, `var` or `const`? What is temporal dead zone?
Done

2024-03-20 10:37 UTC, roblarsen approved these changes

2024-03-20 10:37 UTC, merged

2024-03-20 10:40 UTC, LantingHe commented
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。